# Generated by Django 3.2.6 on 2021-08-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-creation_datetime', 'title'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
